apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wachswork-cert
  namespace: blog
spec:
  commonName: "*.wachs.work"
  secretName: wachswork-cert
  dnsNames:
    - "*.wachs.work"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

