repositories:
  - name: kyverno
    url:  https://kyverno.github.io/kyverno

releases:
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    version: 3.2.1
    installed: true
    wait: true
    timeout: 300
    atomic: true
  - name: policies
    namespace: kyverno
    chart: ./policies
    needs: ["kyverno/kyverno"]
    installed: true
    wait: true
    timeout: 300
    atomic: true
