apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wachswork-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      {{- if .Values.ingress.hosts }}
      {{- range .Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      {{- end }}
      secretName: wachswork-cert-prod
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wachswork
                port:
                  number: 80
    {{- end }}
    {{- end }}
