apiVersion: v1
kind: PersistentVolume
metadata:
  name: wachswork-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/ubuntu/volumes/blog-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vmi1371041.contaboserver.net
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wachswork-pvc
  namespace: wachswork
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 512Mi

