name: Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # Needs permission to create tokens for OIDC
    permissions:
      id-token: write
      contents: read
    steps:
      # Prepare AWS credentials using OIDC provider (uses id-token and contents)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1
      # AWS CLI should already be installed on runner
      - run: aws s3 ls s3://k8s-app-secrets
